language: rust

rust:
    - nightly

cache:
    directories:
        - target

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc

after_success:
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $TRAVIS_RUST_VERSION == "stable" &&
    sh etc/deploy-docs.sh
